name: c_lens_mobile
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2



dependencies:
  flutter:
    sdk: flutter

  # Yüz embedding modeli için
  tflite_flutter: ^0.11.0
  # Görüntü işleme (resize / normalize vs.)
  image: ^4.1.7
  # Kamera erişimif
  camera: ^0.10.5+9
  # Google MLKit yüz algılama
  google_mlkit_face_detection: ^0.11.0
  # UI’daki kaydırmalı switch
  sliding_switch: ^1.1.0
  # Dosya yolları (resim kaydetme vb.)
  path_provider: ^2.1.2
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.3
  mobile_scanner: 5.2.3
  firebase_auth: ^6.1.2

#  cupertino_icons: ^1.0.8
#  toggle_switch: ^2.3.0
#  sliding_switch: ^1.1.0
#  camera: ^0.10.5+9
#  google_mlkit_face_detection: ^0.11.0
#  path_provider: ^2.1.5
#
#  flutter_lints: ^5.0.0
#
#  tflite_flutter: ^0.10.0
#  tflite_flutter_helper: ^0.2.1
#  image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/models/
